### PR TITLE
Added JaCoCo plugin to pom

### PR DESCRIPTION
**Pull request by SvenSeemann**

### CODE REVIEW

**Comment by SvenSeemann** [comment]
@AndreasZaschka, @olivergierke ok to merge?

**Comment by olivergierke** [comment]
Looks good to me? Are you planning to roll out the updated parent in the next couple of days? I'd love to get Salespoint 6.2 GA into it, too. Is Thursday fine with you?

**Comment by SvenSeemann** [comment]
Yes, Thursday is cool for me.

**Comment by olivergierke** [comment]
Merged.

**Pull request closed without merging**
